# Generated by Django 4.0.4 on 2022-05-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=40)),
                ('image_description', models.TextField(max_length=60)),
                ('image_url', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='pictures')),
            ],
        ),
    ]
