# Generated by Django 4.0.4 on 2022-05-29 08:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_image_category_image_location_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
